import Image from "next/image";
import Head from "next/head";
import Link from "next/link";

import Spline from "@splinetool/react-spline";
import styles from "@/styles/home.module.css"

//components
import Navbar from "@/components/NavBar"
import Heading from "@/components/Heading"
import Feature from "@/components/Features"
import Pricing from "@/components/Pricing"
import Newsletter from "@/components/Newsletter"
import Footer from "@/components/Footer"

export default function Home() {
  return (
    <main
      className={styles.mainContainer}
    >
      <Head>
          <title>Orbit</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/asset/image/orbit-logo.jpeg"/>
        </Head>
      <Navbar/>
      <Heading/>      
      <Feature/>
      <Pricing/>
      <Newsletter/>
      <Footer/>
    </main>
  );
}